name: "Deploy application"

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  dc: docker compose -f .github/docker-compose.ci.yml --env-file .github/.env.ci

jobs:
  build:
    runs-on:
      - self-hosted
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Read environment variables from dotenv file
        id: dotenv
        uses: xom9ikk/dotenv@v1.0.2
        with:
          path: .github
          mode: ci

      - name: "Log in container registry"
        uses: docker/login-action@v2
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Build app"
        run: docker build -t ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}-app:main -f Dockerfile/app.dockerfile --no-cache .
      - run: docker push ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}-app:main

      - name: "Build crontab"
        run: docker build -t ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}-crontab:main -f Dockerfile/cron.dockerfile --no-cache .
      - run: docker push ${{ env.DOCKER_REGISTRY }}/${{ env.IMAGE_NAME }}-crontab:main

  deploy:
    runs-on:
      - self-hosted
    needs:
      - build
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - run: ${{ env.dc }} config
      - run: ${{ env.dc }} stop
      - run: ${{ env.dc }} rm -f
      - run: ${{ env.dc }} up -d --remove-orphans
      - run: docker system prune --force
